### ISSUE TITLE
发送图片出现<E> UploadRequest::ossUpload() failed

### ISSUE THREAD

**Issue by ericliang** [maxim-top/maxim-ios#1]
多媒体信息都有涉及，包括图片，视频，语音。

待补充信息：

1. 用DemoApp是否可以复现
2. 错误Response 的具体信息
3. 相关操作 log

**Comment by YuTongHon** [comment]
存在问题：1.

**Comment by YuTongHon** [comment]
排查结果：由于发送单聊消息时，传入的聊天类型是群聊，所以导致上传文件时，上传文件报错。
另外，语音文件上传路径正在解决中。

**Comment by YuTongHon** [comment]
语音文件上传已解决。原因：获取本地文件失败
