### ISSUE TITLE
downloadStatus属性访问崩溃

### ISSUE THREAD

**Issue by yuanke550** [maxim-top/maxim-ios#4]
BMXFileAttachment对象的downloadStatus属性访问崩溃，报野指针错误。
`if (message.contentType == BMXContentTypeVoice) {
BMXVoiceAttachment *voiceAtt = (BMXVoiceAttachment *)message.attachment;
BMXAttachmentDownloadStatus downloadStatus = voiceAtt.downLoadStatus;}`

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   MaxIM                          0x0000000101735bac 0x101358000 + 4053932
1   MaxIM                          0x00000001015ee244 0x101358000 + 2712132
2   MaxIM                          0x0000000101455ff0 0x101358000 + 1040368
3   CoreFoundation                 0x000000019b23a800 0x19b11a000 + 1181696
4   CoreFoundation                 0x000000019b11c3c0 0x19b11a000 + 9152
5   CoreFoundation                 0x000000019b11cff4 0x19b11a000 + 12276
6   MaxIM                          0x00000001015f6544 0x101358000 + 2745668
7   libdispatch.dylib              0x00000001031536f4 0x103150000 + 14068
8   libdispatch.dylib              0x0000000103154c78 0x103150000 + 19576
9   libdispatch.dylib              0x00000001031626fc 0x103150000 + 75516
10  CoreFoundation                 0x000000019b1c4b20 0x19b11a000 + 699168
11  CoreFoundation                 0x000000019b1bfa58 0x19b11a000 + 678488
12  CoreFoundation                 0x000000019b1befb4 0x19b11a000 + 675764
13  GraphicsServices               0x000000019d3c079c 0x19d3b6000 + 42908
14  UIKitCore                      0x00000001c7a20c38 0x1c7164000 + 9161784
15  MaxIM                          0x0000000101513f6c 0x101358000 + 1818476
16  libdyld.dylib                  0x000000019ac828e0 0x19ac81000 + 6368

**Comment by ericliang** [comment]
3.0 版，已解决。
