### ISSUE TITLE
下载运行报错找不到#import <MobileRTC/MobileRTC.h>

### ISSUE THREAD

**Issue by guoqianqian** [maxim-top/maxim-ios#5]

**Comment by ericliang** [comment]
你好，这个问题应该是 Zoom 的 RTC 库没有引入，具体操作稍后会有同事回复你。

**Comment by ericliang** [comment]
你好，由于当前聊天室功能使用 Zoom SDK 演示，你也可以使用任何其他音视频 SDK 替换它。下载操作如下：

1. 从github下载 [Zoom SDK](https://github.com/zoom/zoom-sdk-ios/releases/download/v5.2.42037.1112/ios-mobilertc-all-5.2.42037.1112-clientlog.zip)
2. 解压后将 lib/MobileRTC.framework 目录整体复制到本项目MaxIM目录

README已更新，感谢你的反馈，为其他开发者使用 Demo 提前解决了问题。
