### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by dangercheng** [maxim-top/maxim-ios#6]
1、Zoom SDK 具体拿来做了什么呢？
2、Demo是否可以修改代码替换为自己的key跑起来？
3、自己接入sdk是否可以只接入Zoom SDK ？

**Comment by ericliang** [comment]
你好，关于问题：

1. 只是用来在 Demo 里演示音视频 SDK 的集成；
2. 可以；
3. 我们核心是 IM SDK，因此可以与其他任何音视频 SDK 共同集成，如果只接入 Zoom SDK，参照 Zoom 的示例即可。

祝好
